{% set name = "pinecone" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pinecone/pinecone-{{ version }}.tar.gz
  sha256: feca7ff607706c09ffbd127ec93fa3b7110896b30c0d7a57672da73c69698d53

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}

outputs:
  - name: {{ name }}
    script: install_pinecone.sh
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - pip
      run:
        - python >={{ python_min }}
        - typing_extensions >=3.7.4
        - certifi >=2019.11.17
        - orjson >=3.0.0
        - pinecone-plugin-interface >=0.0.7,<0.1.0
        - python-dateutil >=2.5.3
        - pinecone-plugin-assistant >=1.6.0,<2.0.0
        # most restrictive
        - urllib3 >=1.26.5

    test:
      imports:
        - pinecone
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-grpc
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        # most restrictive
        - grpcio >=1.68.0
        - googleapis-common-protos >=1.66.0
        - lz4 >=3.1.3
        - protobuf >=5.29,<6.0.0
        - protoc-gen-openapiv2 >=0.0.1,<0.1.0

    test:
      imports:
        - pinecone
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

  - name: {{ name }}-with-asyncio
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage(name, max_pin='x.x.x.x.x.x') }}
        - aiohttp >=3.9.0
        - aiohttp-retry >=2.9.1,<3.0.0

    test:
      imports:
        - pinecone
      commands:
        - pip check
      requires:
        - python {{ python_min }}
        - pip

about:
  home: https://www.pinecone.io
  summary: Pinecone client and SDK
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/pinecone-io/pinecone-python-client
  doc_url: https://docs.pinecone.io/guides/get-started/overview

extra:
  recipe-maintainers:
    - isuruf
    - xylar
