{% set name = "pinecone" %}
{% set version = "7.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pinecone-{{ version }}.tar.gz
  sha256: f8448f361806515b6e0e9c4e67ec0b14ce7efdbd98429925f836ee5f6cd83de4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=3.7.4
    # most restrictive
    - urllib3 >=1.26.0
    - certifi >=2019.11.17
    - pinecone-plugin-interface >=0.0.7,<0.0.8
    - python-dateutil >=2.5.3
    - pinecone-plugin-assistant >=1.6.0,<2.0.0
  run_constrained:
    - googleapis-common-protos >=1.66.0
    # most restrictive
    - grpcio >=1.68.0
    - lz4 >=3.1.3
    - protobuf >=5.29,<6.0.0
    - protoc-gen-openapiv2 >=0.0.1,<0.0.2
    - aiohttp >=3.9.0
    - aiohttp-retry >=2.9.1,<3.0.0

test:
  imports:
    - pinecone
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.pinecone.io
  summary: Pinecone client and SDK
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/pinecone-io/pinecone-python-client
  doc_url: https://docs.pinecone.io/guides/get-started/overview

extra:
  recipe-maintainers:
    - isuruf
    - xylar
