{% set name = "pinecone" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pinecone-{{ version }}.tar.gz
  sha256: 8a4c4c12a7ee2e71b79781ec9df3abcfa5f352fd9217c777c3f2c7db2c0870f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=3.7.4
    - urllib3 >=1.26.5
    - tqdm >=4.64.1
    - certifi >=2019.11.17
    - grpcio >=1.59.0
    - pinecone-plugin-interface >=0.0.7,<0.0.8
    - pinecone-plugin-inference >=2.0.0,<4.0.0
    - python-dateutil >=2.5.3
  run_constrained:
    - googleapis-common-protos >=1.53.0
    - lz4 >=3.1.3
    - protobuf >=4.25.0,<5.0.0
    - protoc-gen-openapiv2 >=0.0.1,<0.0.2

test:
  imports:
    - pinecone
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.pinecone.io
  summary: Pinecone client and SDK
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - isuruf
